### ISSUE TITLE
Could not locate clrjit library on single-file self-contained apps

### ISSUE THREAD

**Issue by szszss** [AngelDE98/MonoMod#129]
### Description

When use MonoMod on a single-file self-contained app, it will throw `System.PlatformNotSupportedException: Could not locate clrjit library`. This problem only occurs when both `PublishSingleFile` and `SelfContained` are true. It seems that clrjit is merged into single-file self-contained app and cannot be loaded like separate files.

MonoMod version: MonoModReorg 23.3.2.1
Runtime version: .NET 7.0.2

### Example

Project config:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoModReorg.RuntimeDetour" Version="23.3.2.1" />
  </ItemGroup>

</Project>
```

Program:
```cs
using System;
using MonoMod.Core.Platforms;

public class Program
{
	static void Main(string[] args)
	{
		try
		{
			var _ = PlatformTriple.Current;
			Console.WriteLine("Hello, World!");
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
		}
	}
}
```

When `PublishSingleFile` and `SelfContained` are NOT both true, the program outputs:

```
Hello, World!
```

When `PublishSingleFile` and `SelfContained` are both true, the program outputs:

```
System.PlatformNotSupportedException: Could not locate clrjit library
   at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.GetClrJitPath()
   at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.GetJitObject()
   at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.get_JitObject()
   at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.MonoMod.Core.Utils.IInitialize.Initialize()
   at MonoMod.Core.Platforms.PlatformTriple.InitIfNeeded(Object obj)
   at MonoMod.Core.Platforms.PlatformTriple..ctor(IArchitecture architecture, ISystem system, IRuntime runtime)
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent()
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj)
   at MonoMod.Core.Platforms.PlatformTriple.get_Current()
   at Program.Main(String[] args)
```

**Comment by nike4613** [comment]
Self-contained apps are not supported. In the context of a self-contained application, all assemblies are well-known ahead of time, so IL weaving is possible. IL weaving will also play better with the runtime. 

There are a great deal of difficulties that would be associated with supporting self-contained applications as well, and as the above is a very feasible option, that scenario will likely never be supported.

**Comment by TanShuJun1985** [comment]
Modifying Features in Core21Runtime can bypass clrjit
        
public override RuntimeFeature Features
        {
            get
            {
                var features = base.Features;
                if (!IsSingleFileRuntime)
                    features |= RuntimeFeature.CompileMethodHook;

                return features;
            }
        }

**Comment by nike4613** [comment]
> Modifying Features in Core21Runtime can bypass clrjit
> 
> public override RuntimeFeature Features { get { var features = base.Features; if (!IsSingleFileRuntime) features |= RuntimeFeature.CompileMethodHook;
> 
> ```
>             return features;
>         }
>     }
> ```

The CompileMethod hook is necessary for hooks to be reliable.

**Comment by TanShuJun1985** [comment]
Modify void IInitialize.Initialize() in CoreBaseRuntime

`    void IInitialize.Initialize()
        {
            IsSingleFileRuntime = IsPublishSingleFile();

            if (IsSingleFileRuntime)
            {
                MMDbgLog.Trace(
                    "PublishSingleFile detected. " +
                    "CompileMethodHook will be disabled.");
                return;
            }

            InstallJitHook(JitObject);
        }`

**Comment by nike4613** [comment]
I will refer you to my previous comment:
> In the context of a self-contained application, all assemblies are well-known ahead of time, so IL weaving is possible. IL weaving will also play better with the runtime.

**Comment by TanShuJun1985** [comment]
The solution I have implemented now is that if IsSingleFileRuntime does not use CompileMethod (i.e., clrjit), otherwise modify base.Features to use the built-in API, which can achieve a single-file self-contained Hook.
However, there is still one issue that remains unresolved. When either PublishSingleFile=true or PublishReadyToRun=true is set individually, everything works fine. However, when both PublishSingleFile=true and PublishReadyToRun=true are enabled simultaneously, VirtualProtect encounters an error
