### ISSUE TITLE
`DynamicMethod.returnType` field name changed in .NET 8 previews

### ISSUE THREAD

**Issue by SeeminglyScience** [AngelDE98/MonoMod#136]
This code:

https://github.com/MonoMod/MonoMod/blob/a61eb746b242ca3691fe914825a6cbaa29285281/src/MonoMod.Utils/DMDGenerators/DMDEmitDynamicMethodGenerator.cs#L10-L13

also needs to check for the name `_returnType`. I didn't check when this change occurred, but I can confirm the type initializer fails in .NET 8.0.0-preview.3.23174.8

(there's also an extra <kbd>e</kbd> in the exception message)

**Comment by nike4613** [comment]
We don't currently support .NET 8, but this is a simple enough change to make. I think I'll wait until the release candidates anyway though.

**Comment by SeeminglyScience** [comment]
That's fair. I'm using MonoMod (through Harmony) to mod PowerShell which sim ships with .NET previews. I get that that's an incredibly niche scenario though.

I wouldn't be shocked if there were more changes needed beyond the field change. If I get some spare time I'll see what else might be needed.

**Comment by guneysus** [comment]
Seems `m_returnType` field renamed to `_returnType` so `_DynamicMethod_returnType` returns `null` for .NET 8.0 (preview)


```cs
// System.Reflection.Emit.Lightweight/6.0.0.0
namespace System.Reflection.Emit
{
    public sealed class DynamicMethod : MethodInfo
    {
        private RuntimeType[] m_parameterTypes;
        internal IRuntimeMethodInfo? m_methodHandle;
        private RuntimeType m_returnType;
```


```cs
// System.Reflection.Emit.Lightweight/8.0.0.0
namespace System.Reflection.Emit
{
    public sealed partial class DynamicMethod : MethodInfo
    {
        private RuntimeType[] _parameterTypes;
        internal IRuntimeMethodInfo? _methodHandle;
        private RuntimeType _returnType;
```

Here is a very crude suggestion:

```cs
        private static readonly FieldInfo _DynamicMethod_returnType =
#if NET8_0
        typeof(DynamicMethod).GetField("_returnType", BindingFlags.NonPublic | BindingFlags.Instance)
#else
        typeof(DynamicMethod).GetField("returnType", BindingFlags.NonPublic | BindingFlags.Instance)
#endif
            ?? typeof(DynamicMethod).GetField("m_returnType", BindingFlags.NonPublic | BindingFlags.Instance);
```

**Comment by karanshah-browserstack** [comment]
According to [this](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc1/) , Microsoft is planning to release the support by mid-November. Is there any ETA when we are planning to pick this up, since the rc1 is now out?

**Comment by nike4613** [comment]
I've talked elsewhere about this, but its looking like this won't be high enough priority for me to work on until GA.
