### ISSUE TITLE
Support for access structs from a class

### ISSUE THREAD

**Issue by CoolModder** [AngelDE98/MonoMod#145]
### Description
Hello, I am a modder for TowerFall. I wish for a easy way to get private structs from classes, which would make accessing certain variables a breeze.

### Example
```
var SomethingData = DyanmicData.Get(<Object>);
SomethingData.Set("Something", new Dictionary<int, SomethingData.GetStruct("SomethingPrivate")>);
```

**Comment by nike4613** [comment]
This is outside the scope of MonoMod. Use a publicizer like [this one](https://github.com/BepInEx/BepInEx.AssemblyPublicizer).
