### ISSUE TITLE
MonoMod.RuntimeDetour breaks Rider around tuples on .NET Framework 4.8

### ISSUE THREAD

**Issue by Metadorius** [AngelDE98/MonoMod#147]
### Description
Tuples are no longer recognized as valid types, analysis gives errors about ambigous invocations on methods which use tuples as type params and Rider no longer gives IntelliSense hints.

### Repro
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>11.0</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.0.2" />
    </ItemGroup>
    
</Project>
```
```cs
using System;

var foo = (1, 2);
Console.WriteLine($"{foo.Item1}");
```
Here's what it looks like:
![broken type](https://github.com/MonoMod/MonoMod/assets/17500545/ae23460e-96c4-48e0-a710-86077785ff1f)
![ambiguous invocation](https://github.com/MonoMod/MonoMod/assets/17500545/042f8114-7719-4fb4-833c-e9de8906fcea)

If you remove the reference - everything goes back to normal.

**Comment by nike4613** [comment]
Do these errors manifest from a command-line build? If not, then this is a Rider issue.

**Comment by Metadorius** [comment]
> Do these errors manifest from a command-line build? If not, then this is a Rider issue.

The build is fine and the Visual Studio is fine, it's only an analysis-level issue, it reports as false positive. I am not sure it's a Rider issue exactly and not the interaction between Rider and some MonoMod package specifics. Just to be sure I am reporting it to both parties involved. (And also because it might be a simple fix even considering the issue should probably be fixed on Rider's side, it's just that I am not sure JetBrains has a great track record of bugfixing stuff.)

**Comment by nike4613** [comment]
Unfortunately Rider is full of these kinds of issues, even in entirely normal code. (One notable example I remember is that it handles `nint` and `nuint` weirdly wrt overload resolution, and will complain about ambiguous match when calling a method with `int` and `nint` overloads, despite this being completely well defined according to the C# spec.)

I don't think there's anything I can do here without sacrificing the entire purpose of Backports.

**Comment by Metadorius** [comment]
Maybe I could poke around and come up with some workaround. Do you have any idea on what specifically might cause such behavior?

**Comment by nike4613** [comment]
Best I can give you is that it has to do with `MonoMod.Backports`'s implementation of `DefaultInterpolatedStringHandler`. Only issue is that it was copied almost verbatim out of the BCL circa .NET 6, and only tweaked to get good behavior for certain other types that get good behavior due to other things in newer versions (most notably `(U)IntPtr`)

**Comment by Metadorius** [comment]
Well I got this behavior on almost everything that uses a tuple, not only interpolated strings, here are a few examples:
![image](https://github.com/MonoMod/MonoMod/assets/17500545/82e967ac-dc6b-434d-8c36-bfd0ee051761)
![image](https://github.com/MonoMod/MonoMod/assets/17500545/0f2d39cf-55b8-4118-bbd0-ca71a9c3d520)
Here the key type is the following, notice the missing tuple in intellisense:
![image](https://github.com/MonoMod/MonoMod/assets/17500545/123f8df4-9fa0-436e-be15-f091ca6cdbad)
So it all stems from tuples not being recognized, even in non-BCL stuff (OnNext is from Reactive Extensions).

**Comment by nike4613** [comment]
That sounds like a pretty huge issue with Rider then. Possibly having to do with the type forwards Backports has, when `ValueTuple` already exists.

**Comment by Metadorius** [comment]
Will see if reporting the issue to JetBrains does anything.

**Comment by Metadorius** [comment]
Opened an issue in their bug tracker, let's see: https://youtrack.jetbrains.com/issue/RIDER-101266/Referencing-MonoMod.RuntimeDetour-breaks-analysis-of-ValueTuple-on-.NET-Framework-4.8

**Comment by nike4613** [comment]
It looks like they fixed this.
