### ISSUE TITLE
Mono problems with data transfer via NativeHook

### ISSUE THREAD

**Issue by kohanis** [AngelDE98/MonoMod#157]
### Description

Same repo, second method https://github.com/kohanis/MonoModTest

Assembly.GetExecutingAssembly() is native in mono 6, returning Assembly.GetAssembly(typeof(Assembly)) from hook causes mono to think it's null (kinda), calling trampoline-delegate causes a crash

```cs
public static class Program
{
	private static void MonoTest()
	{
	    var original = Assembly.GetExecutingAssembly();
	
	    var getAssemblyMethod = typeof(Assembly).GetMethod(nameof(Assembly.GetExecutingAssembly), new Type[] { });
	    using var getAssemblyHookNative = new NativeHook(PlatformTriple.Current.GetNativeMethodBody(getAssemblyMethod), GetAssemblyFix);
	
	    var patched = Assembly.GetExecutingAssembly();
	    
	    Helpers.Assert(Equals(original, patched));
	}
	
	delegate Assembly GetAssemblyDelegate();
	
	private static Assembly GetAssemblyFix(GetAssemblyDelegate orig)
	{
	    // return orig();
	    return Assembly.GetAssembly(typeof(Program));
	}
}
```

**Comment by nike4613** [comment]
You should not be using `NativeHook` with a managed signature, even if it's implemented by the runtime.

**Comment by kohanis** [comment]
Makes sense. But is there no way to use it with a hook then? Only with detour? Managed hook will not work because GetMethodBody() is null, obviously
// I apologise if I'm asking some primitive things)

**Comment by nike4613** [comment]
I think at the moment you'll have to use an MM.Core ptr to ptr detour directly, ask it to create an alt entry point, and calli that. Hook doesn't have this support because alt entrypoint creation came after its impl. I do think I want to support it as a fallback if there's no body. 

That being said, detouring fcalls is generally a Bad Idea, though I get the need here.
