### ISSUE TITLE
Arguments passed to a hook from a generic method are shifted by 1

### ISSUE THREAD

**Issue by Kira-NT** [AngelDE98/MonoMod#185]
### Description

Hi! I noticed a strange off-by-one error while trying to hook into a generic method. I understand that this library doesn't fully support generics due to the numerous complications they present. However, this problem does seem like a simple stray `-1` somewhere it shouldn't be, so maybe it can be easily fixed.

### Example

Please consider the following MRE:

```cs
var addLast = typeof(Foo).GetMethod(nameof(Foo.AddLast))!.MakeGenericMethod(typeof(string));
var addLastHook = typeof(FooHook).GetMethod(nameof(FooHook.AddLast))!.MakeGenericMethod(typeof(string));

var hook = new Hook(addLast, addLastHook);

new Foo().AddLast(new(), "Hello world");

// ...

public class Foo
{
    public void AddLast<T>(List<T> list, T item)
    {
        list.Remove(item);
        list.Add(item);
    }
}

public static class FooHook
{
    public static void AddLast<T>(Action<Foo, List<T>, T> addLast, Foo it, List<T> list, T item)
    {
        // `addLast` is fine and works properly.
        //
        // `it` is also fine and indeed appears as a `Foo` instance.
        //
        // `item` is actually `List<T>`, not `T`, while
        // `list` is not even an object.
        //
        // Any attempt to do literally anything with `list`
        // will result in a `NullReferenceException` being thrown.
        // Even operations like `Console.WriteLine(list is List<string>)`!
        addLast(it, list, item);
    }
}
```

In this case, `item` receives a value that was supposed to be passed as `list`, while `list` seemingly hasn't received anything at all and represents a chunk of uninitialized memory *(it is not a valid object, and sometimes I get an `AccessViolationException` for trying to inspect the memory behind it)*.

This pattern continues if we keep adding parameters:
- The callback *(if any)* and the instance reference *(if any)* are set properly.
- The next argument is totally borked.
- The next argument after that receives the value of the previous one.
- The next argument after that receives the value of the previous one, too.
- ...
- The next argument after that receives the value of the previous one, too. 
- There's no way to access the last argument passed to the original method.

I hope you get the idea. Do you have any thoughts on where the problem could stem from?

**Comment by Windows10CE** [comment]
What platform, runtime, and architecture are you using to run this repro

**Comment by Kira-NT** [comment]
.NET 8.0.204 on Linux, 6.8.8-300.fc40.x86_64

**Comment by Windows10CE** [comment]
It's likely a problem with the default ABI definition for that target, will look into it later today
https://github.com/MonoMod/MonoMod/blob/reorganize/src/MonoMod.Core/Platforms/Systems/LinuxSystem.cs#L45

**Comment by Windows10CE** [comment]
Ah, yeah, that definition is missing `SpecialArgumentKind.GenericContext` after `ThisPointer` and before `UserArguments`.
The generic context is this magic extra parameter that you are seeing.

**Comment by Kira-NT** [comment]
> The generic context is this magic extra parameter that you are seeing.

This actually makes sense!

> Ah, yeah, that definition is missing `SpecialArgumentKind.GenericContext` after `ThisPointer` and before `UserArguments`.

This is what I thought too after you pointed out that file. So, I added the `GenericContext` bit myself, recompiled MonoMod, and... the issue persists. Then I inspected definitions for other platforms, and they don't seem to specify the `GenericContext` either. However, judging by code snippets found online and discussions in this repo, simple examples like mine should at least somewhat work on Windows.

**Comment by Kira-NT** [comment]
P.S. - tested this with static generic methods, and they cause the same exact problem.

**Comment by Kira-NT** [comment]
P.P.S. - even without any modifications, `PlatformTriple.Current.Abi` returns `ThisPointer, ReturnBuffer, GenericContext, UserArguments`, so the problem must lie elsewhere, I guess.

**Comment by nike4613** [comment]
MonoMod has **zero** support for patching generics. No guarantees at all are made. There's no generic context handling anywhere, which is why you're seeing this.

**Comment by Kira-NT** [comment]
@nike4613, I know, I know, generics are finicky to work with and yadda-yadda. Just to clarify, nobody is asking to solve some fundamental problems, nor to introduce first-hand support for generics *(like, for example, the ability to hook into a specific generic method implementation)*, nor to even claim that it works on every platform that MonoMod as a whole supports *(like, wow, that's an impressive list, but of course, a fragile and heavily implementation-dependent feature like generics may not work properly everywhere)*. I understand that you are not particularly interested in fixing this specific issue yourself, but are you open to accepting a PR? Because I would love to get this fixed, and I see no harm in leaving things a bit less broken than they were before.

I just wanna say that the current behavior **is** a bug, it **is** an off-by-one error. Well, okay, there are three problems with it actually:
1) As you've just said, there's no generic context handling. However, the existing codebase clearly acknowledges its presence. And that's **more** than enough to make it work maybe not perfectly, but, you know, fine. It's just that nobody has ever bothered to walk those extra few steps.
2) Why do I say that it's a bug? The current code is just proactively wrong. When `PlatformTriple.GetRealDetourTarget` processes `Abi.ArgumentOrder`, it skips `GenericContext` entirely, so no wonder `UserArguments` are off by one after that!

Anyways, I have a working solution on my end *(just need to test and brush it up a bit more)*, and I would be more than happy to turn it into a PR. Once again, I do not see any problems with making things less broken. So, let me know if this is something I should invest my time into or if you are completely against it and I need to resort to ~~violence~~ patching MonoMod with MonoMod :)

**Comment by nike4613** [comment]
I would be interested to see your solution, though I make no promises on whether I'll merge it.

`GenericContext` exists in the argument order largely because I wrote reorg with generics largely in mind, so that it would be reasonable to slot them in to the architecture. (I have a prototype based on legacy which implements generic detour support for **1 (one)** OS/arch/runtime triple. This prototype is also exactly why my response to anything generics related is "don't do that".) My recommendation in general is simply to *not detour generics, period*. The only reason I don't throw if you pass them in is because *sometimes, by chance* it works, and when it does, it's useful. I'm not a fan of half-assed hack-fixes to slightly improve tiny corner cases, because once you stack enough of those on top of each other, you end up with legacy MonoMod, where it's impossible to tell what purpose any of them serve.

**Comment by Kira-NT** [comment]
> `GenericContext` exists in the argument order largely because I wrote reorg with generics largely in mind

And you've done an amazing job here! :) That's why I was initially a bit confused because of something not working as expected *(and in a such explosive way)*, considering the codebase generally acknowledges the existence of generics.

> I'm not a fan of half-assed hack-fixes to slightly improve tiny corner cases

Yup, me neither. My current patch, which introduces an ABI fixup for shared generics, is something that needs to be done either way if MonoMod is going to fully support generic hooks somewhere in the future *(at least I believe so)*. I hoped that it would fit into a small, focused PR; however, I need to add a few bits to `Interop`, and things are not pretty there. So, I either need to first submit a PR that attempts to refactor this whole endeavor, or just throw my stuff on top of everything that currently sits there and make things worse. But I would rather not.

I'm gonna open a new issue to discuss these topics if you don't mind :)
